### ISSUE TITLE
Adding SSLChainApprovalCallback

### ISSUE THREAD

**Issue by edewata** [dogtagpki/jss#283]
The current `SSLCertificateApprovalCallback` has an `approve(X509Certificate, ValidityStatus)` method which provides only the leaf certificate. In some cases the client may need to get the full chain. One possible solution is to provide something like `SSLChainApprovalCallback` with an `approve(X509Certificate[], ValidityStatus)` method which provides the full chain to the client.

**Comment by cipherboy** [comment]
I'm closing this as WONTFIX. The correct way of doing this is with a `X509TrustManager` with a `JSSEngine`.

Alternatively, if functionality is still required, we can extend the BadCert hook, however, this won't work for all use cases (and requires access to the underlying `JSSEngine` -- either directly, or via access to the `JSSSocket`). Note that `X509TrustManager`, while more work, does allow you to implement this even in most APIs which don't provide access to the underlying implementation.
