### ISSUE TITLE
tests failing with nss-3.59

### ISSUE THREAD

**Issue by tjaalton** [dogtagpki/jss#661]
There are some tests that fail with nss-3.59

> 40/75 Test #40: Mozilla_JSS_JCA_Signature .........................***Failed    0.88 sec
> ERROR: ld.so: object 'libfakeroot-sysv.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
> Nov 19, 2020 7:29:38 AM org.mozilla.jss.CryptoManager initialize
> INFO: JSS CryptoManager: successfully initialized from NSS database at /<<PKGBUILDDIR>>/build/results/nssdb
> Provider 0: Mozilla-JSS
> Provider 1: SUN
> Provider 2: SunRsaSign
> Provider 3: SunJSSE
> Provider 4: SunJCE
> Provider 5: JdkSASL
> Provider 6: SunPKCS11
> ***FilePasswordCallback returns m1oZilla
> The provider used to Generate the Keys was Mozilla-JSS
> provider info Provides Signature, Message Digesting, and RNG
> Created a signing context
> The provider used for the signer Mozilla-JSS and the algorithm was MD5/RSA
> Exception in thread "main" java.security.InvalidKeyException: Token exception occurred: Unable to create signing context
> 	at org.mozilla.jss.provider.java.security.JSSSignatureSpi.engineInitSign(JSSSignatureSpi.java:57)
> 	at java.base/java.security.Signature$Delegate.engineInitSign(Signature.java:1351)
> 	at java.base/java.security.Signature.initSign(Signature.java:636)
> 	at org.mozilla.jss.tests.JCASigTest.sigTest(JCASigTest.java:50)
> 	at org.mozilla.jss.tests.JCASigTest.main(JCASigTest.java:104)
> Caused by: org.mozilla.jss.crypto.TokenException: Unable to create signing context
> 	at org.mozilla.jss.pkcs11.PK11Signature.initSigContext(Native Method)
> 	at org.mozilla.jss.pkcs11.PK11Signature.engineInitSign(PK11Signature.java:114)
> 	at org.mozilla.jss.crypto.Signature.initSign(Signature.java:55)
> 	at org.mozilla.jss.provider.java.security.JSSSignatureSpi.engineInitSign(JSSSignatureSpi.java:53)
> 	... 4 more
> 
>       Start 41: Mozilla_JSS_NSS_Signature
> 41/75 Test #41: Mozilla_JSS_NSS_Signature .........................***Failed    0.88 sec
> ERROR: ld.so: object 'libfakeroot-sysv.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
> Nov 19, 2020 7:29:39 AM org.mozilla.jss.CryptoManager initialize
> INFO: JSS CryptoManager: successfully initialized from NSS database at /<<PKGBUILDDIR>>/build/results/nssdb
> Available tokens:
>  token : NSS Generic Crypto Services
>  token : Internal Key Storage Token
> ***FilePasswordCallback returns m1oZilla
> Created a signing context
> Exception in thread "main" org.mozilla.jss.crypto.TokenException: Unable to create signing context
> 	at org.mozilla.jss.pkcs11.PK11Signature.initSigContext(Native Method)
> 	at org.mozilla.jss.pkcs11.PK11Signature.engineInitSign(PK11Signature.java:114)
> 	at org.mozilla.jss.crypto.Signature.initSign(Signature.java:55)
> 	at org.mozilla.jss.tests.SigTest.main(SigTest.java:88)

full log at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=975212

**Comment by cipherboy** [comment]
This should be fixed by #651.
