### ISSUE TITLE
Is it possible to disable FIPS tests?

### ISSUE THREAD

**Issue by blackcross86** [dogtagpki/jss#809]
How to disable tests in cmake (FIPS)

**Comment by fmarco76** [comment]
@blackcross86 did you get the test passing? If yes I will close the issues otherwise could you provide more info on the environment beside NSS which you already provided?

**Comment by fmarco76** [comment]
@blackcross86 I am closing this issue because I cannot replicate the error. If it is still present re-open it and provide more details, please.
